language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-express-kick-starter' ]; then cd .. && eval "mv $currentfolder generator-express-kick-starter" && cd generator-express-kick-starter; fi

