#
# Redis
#
redis:
  session:
    host: localhost
    port: 6379
    db: 0
    ttl: 7776000 # 60 * 60 * 24 * 90 (90days)
    prefix: "sess:"
  db:
    host: localhost
    port: 6379
  session:
    host: localhost
    port: 6379
    db: 0
    ttl: 7776000 # 60 * 60 * 24 * 90 (90days)
    prefix: "sess:"
